"""Public fixed-boundary solver entry points.

This module owns the user-facing fixed-boundary solver wrappers.  The large
VMEC residual-iteration engine lives in ``residual.iteration``; keeping these
wrappers separate makes the residual engine closer to a single-purpose domain
module while preserving the historical ``vmec_jax.solve`` API.
"""

from __future__ import annotations

from typing import Any, Dict

from vmec_jax.solvers.fixed_boundary.residual import iteration as _impl
from vmec_jax.solvers.fixed_boundary.results import SolveFixedBoundaryResult, SolveLambdaResult, SolveVmecResidualResult
from vmec_jax.state import VMECState


def solve_lambda_gd(
    state0: VMECState,
    static,
    *,
    phipf,
    chipf,
    signgs: int,
    lamscale,
    sqrtg: Any | None = None,
    max_iter: int = 50,
    step_size: float = 0.05,
    grad_tol: float | None = None,
    max_backtracks: int = 16,
    bt_factor: float = 0.5,
    jit_grad: bool = False,
    preconditioner: str = "none",
    precond_exponent: float = 1.0,
    precond_radial_alpha: float = 0.0,
    verbose: bool = True,
) -> SolveLambdaResult:
    """Solve VMEC lambda coefficients with fixed R/Z geometry."""

    return _impl._lambda_optimizer_helpers.solve_lambda_gd_impl(
        state0,
        static,
        phipf=phipf,
        chipf=chipf,
        signgs=signgs,
        lamscale=lamscale,
        sqrtg=sqrtg,
        max_iter=max_iter,
        step_size=step_size,
        grad_tol=grad_tol,
        max_backtracks=max_backtracks,
        bt_factor=bt_factor,
        jit_grad=jit_grad,
        preconditioner=preconditioner,
        precond_exponent=precond_exponent,
        precond_radial_alpha=precond_radial_alpha,
        verbose=verbose,
        has_jax_func=_impl.has_jax,
        validate_options_func=_impl.validate_lambda_gd_options,
        mode00_index_func=_impl._mode00_index,
        eval_geom_func=_impl.eval_geom,
        eval_fourier_dtheta_func=_impl.eval_fourier_dtheta,
        eval_fourier_dzeta_phys_func=_impl.eval_fourier_dzeta_phys,
        bsup_from_sqrtg_lambda_func=_impl.bsup_from_sqrtg_lambda,
        angle_steps_func=_impl.angle_steps,
        enforce_lambda_gauge_func=_impl._enforce_lambda_gauge,
        resolve_grad_tol_func=_impl._resolve_grad_tol,
        jax_module=_impl.jax,
        jnp_module=_impl.jnp,
        jit_func=_impl.jit,
    )


def solve_fixed_boundary_gd(
    state0: VMECState,
    static,
    *,
    phipf,
    chipf,
    signgs: int,
    lamscale,
    edge_Rcos: Any | None = None,
    edge_Rsin: Any | None = None,
    edge_Zcos: Any | None = None,
    edge_Zsin: Any | None = None,
    pressure: Any | None = None,
    gamma: float = 0.0,
    jacobian_penalty: float = 1e3,
    max_iter: int = 25,
    step_size: float = 5e-3,
    scale_rz: float = 1.0,
    scale_l: float = 1.0,
    grad_tol: float | None = None,
    max_backtracks: int = 16,
    bt_factor: float = 0.5,
    jit_grad: bool = False,
    preconditioner: str = "none",
    precond_exponent: float = 1.0,
    precond_radial_alpha: float = 0.0,
    differentiable: bool = False,
    stop_grad_in_update: bool = False,
    verbose: bool = True,
) -> SolveFixedBoundaryResult:
    """Minimize a VMEC-style energy objective over fixed-boundary coefficients."""

    return _impl._fixed_boundary_gd_helpers.solve_fixed_boundary_gd_impl(
        state0,
        static,
        phipf=phipf,
        chipf=chipf,
        signgs=signgs,
        lamscale=lamscale,
        edge_Rcos=edge_Rcos,
        edge_Rsin=edge_Rsin,
        edge_Zcos=edge_Zcos,
        edge_Zsin=edge_Zsin,
        pressure=pressure,
        gamma=gamma,
        jacobian_penalty=jacobian_penalty,
        max_iter=max_iter,
        step_size=step_size,
        scale_rz=scale_rz,
        scale_l=scale_l,
        grad_tol=grad_tol,
        max_backtracks=max_backtracks,
        bt_factor=bt_factor,
        jit_grad=jit_grad,
        preconditioner=preconditioner,
        precond_exponent=precond_exponent,
        precond_radial_alpha=precond_radial_alpha,
        differentiable=differentiable,
        stop_grad_in_update=stop_grad_in_update,
        verbose=verbose,
        has_jax_func=_impl.has_jax,
        validate_options_func=_impl.validate_fixed_boundary_gd_options,
        prepare_energy_context_func=_impl._fixed_boundary_energy_helpers.prepare_fixed_boundary_energy_context,
        enforce_fixed_boundary_and_axis_func=_impl._enforce_fixed_boundary_and_axis,
        mask_grad_for_constraints_func=_impl._mask_grad_for_constraints,
        apply_preconditioner_func=_impl._apply_preconditioner,
        update_state_gd_func=_impl._update_state_gd,
        grad_rms_state_func=_impl._grad_rms_state,
        resolve_grad_tol_func=_impl._resolve_grad_tol,
        mode00_index_func=_impl._mode00_index,
        eval_geom_func=_impl.eval_geom,
        bsup_from_geom_func=_impl.bsup_from_geom,
        b2_from_bsup_func=_impl.b2_from_bsup,
        angle_steps_func=_impl.angle_steps,
        validate_pressure_shape_func=_impl.validate_pressure_shape,
        jax_module=_impl.jax,
        jnp_module=_impl.jnp,
        jit_func=_impl.jit,
    )


def solve_fixed_boundary_lbfgs(
    state0: VMECState,
    static,
    *,
    phipf,
    chipf,
    signgs: int,
    lamscale,
    edge_Rcos: Any | None = None,
    edge_Rsin: Any | None = None,
    edge_Zcos: Any | None = None,
    edge_Zsin: Any | None = None,
    pressure: Any | None = None,
    gamma: float = 0.0,
    history_size: int = 10,
    max_iter: int = 40,
    step_size: float = 1.0,
    grad_tol: float | None = None,
    max_backtracks: int = 12,
    bt_factor: float = 0.5,
    jit_grad: bool = False,
    preconditioner: str = "none",
    precond_exponent: float = 1.0,
    precond_radial_alpha: float = 0.0,
    verbose: bool = True,
) -> SolveFixedBoundaryResult:
    """Fixed-boundary energy solve using a dependency-free L-BFGS update."""

    return _impl._fixed_boundary_lbfgs_helpers.solve_fixed_boundary_lbfgs_impl(
        state0,
        static,
        phipf=phipf,
        chipf=chipf,
        signgs=signgs,
        lamscale=lamscale,
        edge_Rcos=edge_Rcos,
        edge_Rsin=edge_Rsin,
        edge_Zcos=edge_Zcos,
        edge_Zsin=edge_Zsin,
        pressure=pressure,
        gamma=gamma,
        history_size=history_size,
        max_iter=max_iter,
        step_size=step_size,
        grad_tol=grad_tol,
        max_backtracks=max_backtracks,
        bt_factor=bt_factor,
        jit_grad=jit_grad,
        preconditioner=preconditioner,
        precond_exponent=precond_exponent,
        precond_radial_alpha=precond_radial_alpha,
        verbose=verbose,
        has_jax_func=_impl.has_jax,
        validate_options_func=_impl.validate_fixed_boundary_lbfgs_options,
        prepare_energy_context_func=_impl._fixed_boundary_energy_helpers.prepare_fixed_boundary_energy_context,
        enforce_fixed_boundary_and_axis_func=_impl._enforce_fixed_boundary_and_axis,
        mask_grad_for_constraints_func=_impl._mask_grad_for_constraints,
        apply_preconditioner_func=_impl._apply_preconditioner,
        grad_rms_state_func=_impl._grad_rms_state,
        resolve_grad_tol_func=_impl._resolve_grad_tol,
        lbfgs_two_loop_direction_func=_impl._lbfgs_two_loop_direction,
        ensure_descent_direction_func=_impl._ensure_descent_direction,
        resolve_lbfgs_curvature_tol_func=_impl._resolve_lbfgs_curvature_tol,
        pack_state_func=_impl.pack_state,
        unpack_state_func=_impl.unpack_state,
        mode00_index_func=_impl._mode00_index,
        eval_geom_func=_impl.eval_geom,
        bsup_from_geom_func=_impl.bsup_from_geom,
        b2_from_bsup_func=_impl.b2_from_bsup,
        angle_steps_func=_impl.angle_steps,
        validate_pressure_shape_func=_impl.validate_pressure_shape,
        jnp_module=_impl.jnp,
        jit_func=_impl.jit,
    )


def solve_fixed_boundary_lbfgs_vmec_residual(
    state0: VMECState,
    static,
    *,
    indata,
    signgs: int,
    w_rz: float = 1.0,
    w_l: float = 1.0,
    include_constraint_force: bool = True,
    objective_scale: float | None = None,
    apply_m1_constraints: bool = True,
    history_size: int = 10,
    max_iter: int = 40,
    step_size: float = 1.0,
    scale_rz: float = 1.0,
    scale_l: float = 1.0,
    grad_tol: float | None = None,
    max_backtracks: int = 12,
    bt_factor: float = 0.5,
    jit_grad: bool = False,
    preconditioner: str = "none",
    precond_exponent: float = 1.0,
    precond_radial_alpha: float = 0.0,
    verbose: bool = True,
) -> SolveVmecResidualResult:
    """Fixed-boundary solve by minimizing the VMEC force-residual objective."""

    return _impl._residual_lbfgs_helpers.solve_fixed_boundary_lbfgs_vmec_residual_impl(
        state0,
        static,
        indata=indata,
        signgs=signgs,
        w_rz=w_rz,
        w_l=w_l,
        include_constraint_force=include_constraint_force,
        objective_scale=objective_scale,
        apply_m1_constraints=apply_m1_constraints,
        history_size=history_size,
        max_iter=max_iter,
        step_size=step_size,
        scale_rz=scale_rz,
        scale_l=scale_l,
        grad_tol=grad_tol,
        max_backtracks=max_backtracks,
        bt_factor=bt_factor,
        jit_grad=jit_grad,
        preconditioner=preconditioner,
        precond_exponent=precond_exponent,
        precond_radial_alpha=precond_radial_alpha,
        verbose=verbose,
        has_jax_func=_impl.has_jax,
        validate_options_func=_impl.validate_residual_lbfgs_options,
        prepare_residual_force_context_func=_impl._residual_force_context_helpers.prepare_residual_force_context,
        mode00_index_func=_impl._mode00_index,
        half_mesh_from_full_mesh_func=_impl._half_mesh_from_full_mesh,
        mass_half_mesh_from_indata_func=_impl._mass_half_mesh_from_indata,
        pressure_half_mesh_from_indata_func=_impl._pressure_half_mesh_from_indata,
        icurv_full_mesh_from_indata_func=_impl._icurv_full_mesh_from_indata,
        vmec_force_flux_profiles_func=_impl._vmec_force_flux_profiles,
        wout_like_cls=_impl._WoutLikeVmecForces,
        assemble_residual_objective_terms_func=_impl._assemble_residual_objective_terms,
        enforce_fixed_boundary_and_axis_func=_impl._enforce_fixed_boundary_and_axis,
        mask_grad_for_constraints_func=_impl._mask_grad_for_constraints,
        apply_preconditioner_func=_impl._apply_preconditioner,
        grad_rms_state_func=_impl._grad_rms_state,
        resolve_grad_tol_func=_impl._resolve_grad_tol,
        lbfgs_two_loop_direction_func=_impl._lbfgs_two_loop_direction,
        ensure_descent_direction_func=_impl._ensure_descent_direction,
        resolve_lbfgs_curvature_tol_func=_impl._resolve_lbfgs_curvature_tol,
        pack_state_func=_impl.pack_state,
        unpack_state_func=_impl.unpack_state,
        jax_module=_impl.jax,
        jnp_module=_impl.jnp,
        jit_func=_impl.jit,
    )


def solve_fixed_boundary_gn_vmec_residual(
    state0: VMECState,
    static,
    *,
    indata,
    signgs: int,
    w_rz: float = 1.0,
    w_l: float = 1.0,
    include_constraint_force: bool = True,
    apply_m1_constraints: bool = True,
    objective_scale: float | None = None,
    damping: float | None = None,
    damping_increase: float = 10.0,
    damping_decrease: float = 0.5,
    max_damping: float | None = None,
    max_retries: int = 6,
    zero_m1_iters: int | None = None,
    zero_m1_fsqz_thresh: float | None = None,
    max_iter: int = 20,
    cg_tol: float | None = None,
    cg_maxiter: int = 80,
    step_size: float = 1.0,
    max_backtracks: int = 12,
    bt_factor: float = 0.5,
    jit_kernels: bool = True,
    verbose: bool = True,
) -> SolveVmecResidualResult:
    """Fixed-boundary solve using Gauss-Newton on VMEC residual blocks."""

    return _impl._residual_gn_helpers.solve_fixed_boundary_gn_vmec_residual_impl(
        state0,
        static,
        indata=indata,
        signgs=signgs,
        w_rz=w_rz,
        w_l=w_l,
        include_constraint_force=include_constraint_force,
        apply_m1_constraints=apply_m1_constraints,
        objective_scale=objective_scale,
        damping=damping,
        damping_increase=damping_increase,
        damping_decrease=damping_decrease,
        max_damping=max_damping,
        max_retries=max_retries,
        zero_m1_iters=zero_m1_iters,
        zero_m1_fsqz_thresh=zero_m1_fsqz_thresh,
        max_iter=max_iter,
        cg_tol=cg_tol,
        cg_maxiter=cg_maxiter,
        step_size=step_size,
        max_backtracks=max_backtracks,
        bt_factor=bt_factor,
        jit_kernels=jit_kernels,
        verbose=verbose,
        has_jax_func=_impl.has_jax,
        validate_options_func=_impl.validate_residual_gn_options,
        prepare_residual_force_context_func=_impl._residual_force_context_helpers.prepare_residual_force_context,
        mode00_index_func=_impl._mode00_index,
        half_mesh_from_full_mesh_func=_impl._half_mesh_from_full_mesh,
        mass_half_mesh_from_indata_func=_impl._mass_half_mesh_from_indata,
        pressure_half_mesh_from_indata_func=_impl._pressure_half_mesh_from_indata,
        icurv_full_mesh_from_indata_func=_impl._icurv_full_mesh_from_indata,
        vmec_force_flux_profiles_func=_impl._vmec_force_flux_profiles,
        wout_like_cls=_impl._WoutLikeVmecForces,
        assemble_residual_objective_terms_func=_impl._assemble_residual_objective_terms,
        residual_objective_vector_func=_impl._residual_objective_vector,
        enforce_fixed_boundary_and_axis_func=_impl._enforce_fixed_boundary_and_axis,
        mask_grad_for_constraints_func=_impl._mask_grad_for_constraints,
        grad_rms_state_func=_impl._grad_rms_state,
        resolve_cg_tol_func=_impl._resolve_cg_tol,
        resolve_lm_damping_func=_impl._resolve_lm_damping,
        dtype_tiny_func=_impl._dtype_tiny,
        pack_state_func=_impl.pack_state,
        unpack_state_func=_impl.unpack_state,
        jax_module=_impl.jax,
        jnp_module=_impl.jnp,
        jit_func=_impl.jit,
    )


def first_step_diagnostics(
    state0: VMECState,
    static,
    *,
    indata,
    signgs: int,
    step_size: float | None = None,
    include_constraint_force: bool = True,
    apply_m1_constraints: bool = True,
    precond_radial_alpha: float = 0.5,
    precond_lambda_alpha: float = 0.5,
    mode_diag_exponent: float = 1.0,
    include_edge: bool = True,
    zero_m1: bool = True,
    use_axisymmetric_preconditioner: bool = False,
) -> Dict[str, Any]:
    """Return a one-step force/precondition/update diagnostic bundle."""

    return _impl._first_step_diagnostics_helpers.first_step_diagnostics_impl(
        state0,
        static,
        indata=indata,
        signgs=signgs,
        step_size=step_size,
        include_constraint_force=include_constraint_force,
        apply_m1_constraints=apply_m1_constraints,
        precond_radial_alpha=precond_radial_alpha,
        precond_lambda_alpha=precond_lambda_alpha,
        mode_diag_exponent=mode_diag_exponent,
        include_edge=include_edge,
        zero_m1=zero_m1,
        use_axisymmetric_preconditioner=use_axisymmetric_preconditioner,
        has_jax_func=_impl.has_jax,
        mode00_index_func=_impl._mode00_index,
        half_mesh_from_full_mesh_func=_impl._half_mesh_from_full_mesh,
        mass_half_mesh_from_indata_func=_impl._mass_half_mesh_from_indata,
        pressure_half_mesh_from_indata_func=_impl._pressure_half_mesh_from_indata,
        icurv_full_mesh_from_indata_func=_impl._icurv_full_mesh_from_indata,
        vmec_force_flux_profiles_func=_impl._vmec_force_flux_profiles,
        zero_edge_rz_force_blocks_func=_impl._zero_edge_rz_force_blocks,
        radial_tridi_smooth_dirichlet_func=_impl._radial_tridi_smooth_dirichlet,
        metric_surface_precond_scales_np_func=_impl._metric_surface_precond_scales_np,
        wout_like_vmec_forces_cls=_impl._WoutLikeVmecForces,
    )


__all__ = (
    "first_step_diagnostics",
    "solve_fixed_boundary_gd",
    "solve_fixed_boundary_gn_vmec_residual",
    "solve_fixed_boundary_lbfgs",
    "solve_fixed_boundary_lbfgs_vmec_residual",
    "solve_lambda_gd",
)
