"""vmec_jax: a JAX implementation of VMEC2000 for fixed and free-boundary equilibria."""

from importlib.metadata import PackageNotFoundError as _PackageNotFoundError
from importlib.metadata import version as _package_version
from importlib import import_module as _import_module
import os as _os
from pathlib import Path as _Path

from ._compat import _default_compilation_cache_dir as _default_jax_cache_dir


def _source_tree_version() -> str | None:
    pyproject = _Path(__file__).resolve().parents[1] / "pyproject.toml"
    if not pyproject.exists():
        return None
    in_project = False
    for raw_line in pyproject.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if line == "[project]":
            in_project = True
            continue
        if in_project and line.startswith("["):
            return None
        if in_project and line.startswith("version"):
            return line.split("=", 1)[1].strip().strip('"')
    return None


try:
    __version__ = _source_tree_version() or _package_version("vmec-jax")
except _PackageNotFoundError:  # pragma: no cover - source tree without installed metadata.
    __version__ = "0+unknown"

# Suppress noisy C++ warnings from XLA/PjRt backend (e.g. repeated
# "Assume version compatibility. PjRt-IFRT does not track XLA executable
# versions." on persistent-cache hits). Must be set before *any* ``import
# jax`` in the process. Uses setdefault so the user can still override via the
# environment.
_os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")
_os.environ.setdefault("ABSL_MIN_LOG_LEVEL", "2")
_os.environ.setdefault("GLOG_minloglevel", "2")

# Enable JAX persistent XLA compilation cache in a machine-scoped directory
# when requested by the backend/env policy in _compat. Accelerator runs use the
# cache by default; CPU runs are opt-in to avoid XLA:CPU AOT feature-mismatch
# warnings on shared or changing runtime environments.
import jax as _jax
_jax_cache_dir = _default_jax_cache_dir()
if _jax_cache_dir is not None:
    _os.makedirs(_jax_cache_dir, exist_ok=True)
    _jax.config.update("jax_enable_compilation_cache", True)
    _jax.config.update("jax_compilation_cache_dir", _jax_cache_dir)

from .namelist import read_indata, write_indata, InData, minimal_fixed_boundary_indata
from .config import FreeBoundaryConfig, VMECConfig, load_config
from .modes import ModeTable, vmec_mode_table, nyquist_mode_table, default_grid_sizes
from .grids import AngleGrid, make_angle_grid
from .boundary import (
    BoundaryCoeffs,
    boundary_from_indata,
    boundary_input_from_indata,
    boundary_from_input_convention,
    boundary_aspect_ratio,
    boundary_aspect_ratio_from_static,
)
from .fourier import (
    HelicalBasis,
    build_helical_basis,
    eval_fourier,
    eval_fourier_dtheta,
    eval_fourier_dzeta_phys,
)
from .driver import (
    ExampleData,
    FixedBoundaryRun,
    example_paths,
    load_example,
    load_input,
    load_wout,
    run_free_boundary,
    run_fixed_boundary,
    solve_fixed_boundary_from_boundary,
    save_npz,
    residual_scalars_from_state,
    write_wout_from_fixed_boundary_run,
    wout_from_fixed_boundary_run,
)
from .booz_input import booz_xform_inputs_from_state
from .wout import equilibrium_aspect_ratio_from_state, equilibrium_iota_profiles_from_state
from .state import VMECState, pack_state, unpack_state
from .static import VMECStatic, build_static
from .free_boundary import (
    FreeBoundaryRuntimeState,
    MGridMetadata,
    MGridData,
    PreparedMGrid,
    VacuumBoundaryFields,
    ExternalBoundarySample,
    NestorPoissonCache,
    NestorVmecLikeCache,
    NestorRuntimeState,
    NestorSolveResult,
    boundary_metric_from_rz,
    covariant_boundary_field_from_cylindrical,
    contravariant_boundary_field_from_covariant,
    vacuum_boundary_fields_from_cylindrical,
    sample_free_boundary_external_field as sample_free_boundary_external_field,
    sample_external_vacuum_diagnostics,
    nestor_external_only_step,
    initial_free_boundary_state,
    interpolate_mgrid_bfield,
    load_mgrid,
    prepare_mgrid_for_config,
    validate_free_boundary_config,
)
from .init_guess import extract_axis_override_from_state, initial_guess_from_boundary
from .optimization import (
    BoundaryParamSpec,
    FixedBoundaryContext,
    FixedBoundaryExactOptimizer,
    apply_boundary_params,
    boundary_param_names,
    boundary_param_specs,
    create_x_scale,
    extend_boundary_for_max_mode,
    gauss_newton_least_squares,
    lift_boundary_params,
    make_qh_residuals_fn,
    make_qs_residuals_fn,
    parse_surface_list,
    prepare_fixed_boundary_context,
    smooth_min_abs_iota_residual,
    surface_indices_from_s,
    surface_indices_from_static,
    truncate_indata_boundary_modes,
)
from .coords import Coords, eval_coords
from .geom import Geom, eval_geom
from .profiles import (
    ELEMENTARY_CHARGE,
    Profile,
    ProfileInputs,
    ProfilePolynomial,
    ProfilePressure,
    ProfileScaled,
    StandardFiniteBetaProfiles,
    eval_profiles,
    pressure_profile_to_vmec_am,
    profile_to_power_series_coeffs,
    profiles_from_indata,
    standard_finite_beta_profiles,
    standard_pressure_profile,
    with_pressure_profile,
)
from .finite_beta import (
    FiniteBetaTargets,
    finite_beta_global_residuals_from_state,
    finite_beta_scalars_from_state,
    jxbforce_profiles_from_realspace,
    magnetic_well_from_state,
    magnetic_well_from_vp,
    mercier_bss_geometry_channels_from_state,
    mercier_bss_half_mesh_geometry_from_realspace,
    mercier_bsubs_derivatives_lasym_false,
    mercier_bsubs_derivatives_lasym_true,
    mercier_bsubs_full_mesh_from_half_mesh,
    mercier_bsubs_half_mesh_from_geometry,
    mercier_bdotk_from_covariant_derivatives,
    mercier_gpp_from_realspace_geometry,
    mercier_realspace_geometry_channels_from_state,
    mercier_surface_integrals_from_realspace,
    mercier_terms_from_state,
    mercier_terms_from_profile_integrals,
    mercier_zeta_half_mesh_from_realspace_geometry,
    polynomial_profile_and_derivative,
    redl_bootstrap_geometry_from_state,
    redl_bootstrap_jdotb,
    redl_bootstrap_mismatch_from_profiles,
    redl_bootstrap_mismatch_from_state,
    trapped_fraction_from_modb_sqrtg,
)
from .bootstrap_current import (
    BootstrapCurrentIteration,
    BootstrapCurrentOptions,
    BootstrapCurrentResult,
    apply_current_profile_to_indata,
    bootstrap_current_fixed_point,
    bootstrap_current_update_to_indata,
    damp_current_profile,
    dpsi_ds_from_vmec_phiedge,
    integrate_current_derivative,
    redl_current_derivative_update,
    redl_current_integrating_factor_update,
    redl_current_rhs,
    vmec_current_profile_from_bootstrap_update,
)
from .mercier import glasser_resistive_interchange_from_mercier_terms
from .integrals import dvds_from_sqrtg, cumtrapz_s, volume_from_sqrtg
from .field import (
    b_cartesian_from_state,
    b2_from_bsup,
    bsup_from_geom,
    bsup_from_sqrtg_lambda,
    signgs_from_sqrtg,
)
from .energy import magnetic_wb_from_state, flux_profiles_from_indata
from .diagnostics import Summary, print_jacobian_stats, print_summary, summarize_array, summarize_many
from .vmec_jacobian import vmec_half_mesh_jacobian_from_state
from .vmec_realspace import vmec_realspace_analysis, vmec_realspace_geom_from_state
from .preconditioner_1d_jax import clear_preconditioner_jit_caches
from .solve import (
    SolveFixedBoundaryResult,
    SolveLambdaResult,
    solve_fixed_boundary_gd,
    solve_fixed_boundary_lbfgs,
    solve_fixed_boundary_lbfgs_vmec_residual,
    solve_fixed_boundary_gn_vmec_residual,
    solve_fixed_boundary_residual_iter,
    solve_lambda_gd,
)
from .residuals import ForceResiduals, force_residuals_from_state
from .quasisymmetry import (
    quasisymmetry_diagnostics_from_state,
    quasisymmetry_ratio_residual_from_state,
    quasisymmetry_ratio_residual_from_wout,
)

_LAZY_ATTRS = {
    "api": ".api",
    "FreeBoundaryRuntimeState": ".free_boundary",
    "MGridMetadata": ".free_boundary",
    "MGridData": ".free_boundary",
    "PreparedMGrid": ".free_boundary",
    "VacuumBoundaryFields": ".free_boundary",
    "ExternalBoundarySample": ".free_boundary",
    "NestorPoissonCache": ".free_boundary",
    "NestorVmecLikeCache": ".free_boundary",
    "NestorRuntimeState": ".free_boundary",
    "NestorSolveResult": ".free_boundary",
    "boundary_metric_from_rz": ".free_boundary",
    "covariant_boundary_field_from_cylindrical": ".free_boundary",
    "contravariant_boundary_field_from_covariant": ".free_boundary",
    "vacuum_boundary_fields_from_cylindrical": ".free_boundary",
    "sample_free_boundary_external_field": ".free_boundary",
    "sample_external_vacuum_diagnostics": ".free_boundary",
    "nestor_external_only_step": ".free_boundary",
    "initial_free_boundary_state": ".free_boundary",
    "interpolate_mgrid_bfield": ".free_boundary",
    "load_mgrid": ".free_boundary",
    "prepare_mgrid_for_config": ".free_boundary",
    "validate_free_boundary_config": ".free_boundary",
    "SurfaceData": ".plotting",
    "axis_rz_from_wout": ".plotting",
    "axis_rz_from_wout_physical": ".plotting",
    "axis_rz_from_state_physical": ".plotting",
    "bmag_from_wout": ".plotting",
    "bmag_from_wout_physical": ".plotting",
    "bmag_from_state_physical": ".plotting",
    "bmag_from_state_vmec_realspace": ".plotting",
    "bsup_from_wout": ".plotting",
    "bsub_from_wout": ".plotting",
    "boozer_bmag_grid_from_state": ".plotting",
    "closed_theta_grid": ".plotting",
    "fix_matplotlib_3d": ".plotting",
    "profiles_from_wout": ".plotting",
    "select_zeta_slices": ".plotting",
    "surface_data_from_wout": ".plotting",
    "surface_rz_from_wout": ".plotting",
    "surface_rz_from_wout_physical": ".plotting",
    "surface_rz_from_state": ".plotting",
    "surface_rz_from_state_physical": ".plotting",
    "surface_stack": ".plotting",
    "plot_3d_boundary_comparison": ".plotting",
    "plot_bmag_contours": ".plotting",
    "plot_boozmn": ".plotting",
    "plot_boozmn_bmag_contours": ".plotting",
    "plot_boozmn_mode_families": ".plotting",
    "plot_boozmn_spectrum": ".plotting",
    "plot_boozer_bmag_contours_from_state": ".plotting",
    "plot_boozer_lcfs_bmag_comparison": ".plotting",
    "plot_objective_history": ".plotting",
    "plot_qh_optimization": ".plotting",
    "plot_wout": ".plotting",
    "vmecplot2_bmag_grid": ".plotting",
    "vmecplot2_cross_section_indices": ".plotting",
    "vmecplot2_lcfs_3d_grid": ".plotting",
    "vmecplot2_surface_grid": ".plotting",
    "write_axisym_overview": ".plotting",
    "write_bmag_parity_figures": ".plotting",
    "write_bsub_parity_figures": ".plotting",
    "write_bsup_parity_figures": ".plotting",
    "zeta_grid": ".plotting",
    "zeta_grid_field_period": ".plotting",
    "BoozConfig": ".booz",
    "parse_booz_surfaces": ".booz",
    "read_booz_config": ".booz",
    "resolve_boozmn_path": ".booz",
    "run_booz_xform": ".booz",
    "QIOptimizationContext": ".qi_optimization",
    "apply_qi_example_cli_overrides": ".qi_optimization",
    "diagnostic_float": ".qi_optimization",
    "jsonable": ".qi_optimization",
    "make_qi_optimization_context": ".qi_optimization",
    "qi_diagnostics_for_result": ".qi_optimization",
    "qi_engineering_constraint_tuples": ".qi_optimization",
    "qi_stage_modes": ".qi_optimization",
    "run_boundary_reference_preconditioner": ".qi_optimization",
    "run_qi_stage_policy": ".qi_optimization",
    "run_target_helicity_seed_preconditioner": ".qi_optimization",
    "save_raw_seed_initial_artifacts": ".qi_optimization",
    "target_helicity_seed_terms": ".qi_optimization",
    "AbsMeanIotaFloor": ".optimization_workflow",
    "AbsMeanIotaCeiling": ".optimization_workflow",
    "AspectRatio": ".optimization_workflow",
    "AugmentedLagrangianConstraint": ".optimization_workflow",
    "BVector": ".optimization_workflow",
    "BDotB": ".optimization_workflow",
    "BDotGradV": ".optimization_workflow",
    "BetaTotal": ".optimization_workflow",
    "BoozerBTarget": ".optimization_workflow",
    "BoundaryModeLimits": ".optimization_workflow",
    "DMerc": ".optimization_workflow",
    "FixedBoundaryOptimizationResult": ".optimization_workflow",
    "FixedBoundaryVMEC": ".optimization_workflow",
    "GlasserResistiveInterchange": ".optimization_workflow",
    "JDotB": ".optimization_workflow",
    "JVector": ".optimization_workflow",
    "LeastSquaresProblem": ".optimization_workflow",
    "LgradB": ".optimization_workflow",
    "MagneticWell": ".optimization_workflow",
    "MaxElongation": ".optimization_workflow",
    "MeanIota": ".optimization_workflow",
    "MirrorRatio": ".optimization_workflow",
    "VMECMirrorRatio": ".optimization_workflow",
    "ObjectiveTerm": ".optimization_workflow",
    "OptimizationOutputPaths": ".optimization_workflow",
    "QuasiIsodynamicOptions": ".optimization_workflow",
    "QuasiIsodynamicResidual": ".optimization_workflow",
    "QuasiIsodynamicResidualCeiling": ".optimization_workflow",
    "QuasisymmetryRatioResidual": ".optimization_workflow",
    "QIObjectiveTerm": ".optimization_workflow",
    "RedlBootstrapMismatch": ".optimization_workflow",
    "StageContext": ".optimization_workflow",
    "ToroidalCurrent": ".optimization_workflow",
    "ToroidalCurrentGradient": ".optimization_workflow",
    "abs_mean_iota_floor_objective": ".optimization_workflow",
    "abs_mean_iota_ceiling_objective": ".optimization_workflow",
    "aspect_objective": ".optimization_workflow",
    "boozer_b_target_from_wout": ".optimization_workflow",
    "describe_boundary_mode_limits": ".optimization_workflow",
    "lgradb_objective": ".optimization_workflow",
    "interpolate_indata_boundary": ".optimization_workflow",
    "least_squares_solve": ".optimization_workflow",
    "mean_iota_objective": ".optimization_workflow",
    "normalize_boundary_mode_limits": ".optimization_workflow",
    "optimization_output_paths": ".optimization_workflow",
    "prepare_simple_omnigenity_seed_input": ".optimization_workflow",
    "qs_stage_modes": ".optimization_workflow",
    "qi_boozer_b_target_objective": ".optimization_workflow",
    "qi_lgradb_objective": ".optimization_workflow",
    "qi_max_elongation_constraint": ".optimization_workflow",
    "qi_max_elongation_objective": ".optimization_workflow",
    "qi_mirror_ratio_constraint": ".optimization_workflow",
    "qi_mirror_ratio_objective": ".optimization_workflow",
    "quasi_isodynamic_field_objective": ".optimization_workflow",
    "quasisymmetry_objective": ".optimization_workflow",
    "rebuild_for_optimization_resolution": ".optimization_workflow",
    "repeated_stage_modes": ".optimization_workflow",
    "run_fixed_boundary_objective_optimization": ".optimization_workflow",
    "run_quasi_isodynamic_objective_optimization": ".optimization_workflow",
    "save_optimization_result": ".optimization_workflow",
    "simple_omnigenity_seed_indata": ".optimization_workflow",
    "VolavgB": ".optimization_workflow",
    "ImplicitFixedBoundaryOptions": ".implicit",
    "ImplicitLambdaOptions": ".implicit",
    "solve_fixed_boundary_state_implicit": ".implicit",
    "solve_lambda_state_implicit": ".implicit",
    "ResidualCheckpointTape": ".discrete_adjoint",
    "ResidualIterationTrace": ".discrete_adjoint",
    "build_residual_checkpoint_tape": ".discrete_adjoint",
    "build_residual_checkpoint_tape_direct": ".discrete_adjoint",
    "clear_replay_scan_caches": ".discrete_adjoint",
    "checkpoint_tape_param_jvp": ".discrete_adjoint",
    "checkpoint_tape_param_vjp": ".discrete_adjoint",
    "checkpoint_tape_state_jvp": ".discrete_adjoint",
    "checkpoint_tape_state_jvp_columns": ".discrete_adjoint",
    "checkpoint_tape_state_vjp": ".discrete_adjoint",
    "concat_residual_iteration_traces": ".discrete_adjoint",
    "preconditioned_force_channels_from_raw_forces": ".discrete_adjoint",
    "preconditioned_force_channels_from_rz_output": ".discrete_adjoint",
    "raw_force_residual_from_state": ".discrete_adjoint",
    "replay_residual_checkpoint_step": ".discrete_adjoint",
    "state_dependent_preconditioner_from_forces": ".discrete_adjoint",
    "strict_update_accepted_step": ".discrete_adjoint",
    "strict_update_one_step_from_state": ".discrete_adjoint",
    "strict_update_velocity_block": ".discrete_adjoint",
    "strict_update_velocity_limit": ".discrete_adjoint",
    "strict_update_velocity_state_advance": ".discrete_adjoint",
    "residual_iteration_trace_from_result": ".discrete_adjoint",
    "max_elongation_penalty_from_state": ".quasi_isodynamic",
    "mirror_ratio_penalty_from_boozer_modes": ".quasi_isodynamic",
    "mirror_ratio_penalty_from_boozer_output": ".quasi_isodynamic",
    "quasi_isodynamic_residual_from_boozer_modes": ".quasi_isodynamic",
    "quasi_isodynamic_residual_from_boozer_output": ".quasi_isodynamic",
    "quasi_isodynamic_residual_from_state": ".quasi_isodynamic",
    "legacy_qi_branch_shuffle_diagnostic_from_boozer_output": ".qi_legacy",
    "QI_DIAGNOSTIC_VERSION": ".qi_diagnostics",
    "QIDiagnosticOptions": ".qi_diagnostics",
    "QISeedSuitabilityTargets": ".qi_diagnostics",
    "annotate_qi_seed_suitability": ".qi_diagnostics",
    "qi_cleanup_candidate_promotable": ".qi_diagnostics",
    "qi_diagnostics_from_boozer_output": ".qi_diagnostics",
    "qi_diagnostics_from_state": ".qi_diagnostics",
    "qi_promotion_score": ".qi_diagnostics",
    "rank_qi_seed_records": ".qi_diagnostics",
    "export_vtk_surface_and_fieldline": ".visualization",
}


def __getattr__(name: str):
    module_name = _LAZY_ATTRS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = _import_module(module_name, __name__)
    if name == "api":
        value = module
    else:
        value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__():
    return sorted(set(globals()) | set(_LAZY_ATTRS))

__all__ = [
    "api",
    "read_indata",
    "write_indata",
    "InData",
    "minimal_fixed_boundary_indata",
    "FreeBoundaryConfig",
    "VMECConfig",
    "load_config",
    "ModeTable",
    "vmec_mode_table",
    "nyquist_mode_table",
    "default_grid_sizes",
    "AngleGrid",
    "make_angle_grid",
    "BoundaryCoeffs",
    "boundary_from_indata",
    "boundary_input_from_indata",
    "boundary_from_input_convention",
    "boundary_aspect_ratio",
    "boundary_aspect_ratio_from_static",
    "HelicalBasis",
    "build_helical_basis",
    "eval_fourier",
    "eval_fourier_dtheta",
    "eval_fourier_dzeta_phys",
    "SurfaceData",
    "axis_rz_from_wout",
    "axis_rz_from_wout_physical",
    "axis_rz_from_state_physical",
    "bmag_from_wout",
    "bmag_from_wout_physical",
    "bmag_from_state_physical",
    "bmag_from_state_vmec_realspace",
    "bsup_from_wout",
    "bsub_from_wout",
    "boozer_bmag_grid_from_state",
    "closed_theta_grid",
    "fix_matplotlib_3d",
    "profiles_from_wout",
    "select_zeta_slices",
    "surface_data_from_wout",
    "surface_rz_from_wout",
    "surface_rz_from_wout_physical",
    "surface_rz_from_state",
    "surface_rz_from_state_physical",
    "surface_stack",
    "plot_3d_boundary_comparison",
    "plot_bmag_contours",
    "plot_boozmn",
    "plot_boozmn_bmag_contours",
    "plot_boozmn_mode_families",
    "plot_boozmn_spectrum",
    "plot_boozer_bmag_contours_from_state",
    "plot_boozer_lcfs_bmag_comparison",
    "plot_objective_history",
    "plot_qh_optimization",
    "plot_wout",
    "vmecplot2_bmag_grid",
    "vmecplot2_cross_section_indices",
    "vmecplot2_lcfs_3d_grid",
    "vmecplot2_surface_grid",
    "write_axisym_overview",
    "write_bmag_parity_figures",
    "write_bsub_parity_figures",
    "write_bsup_parity_figures",
    "zeta_grid",
    "zeta_grid_field_period",
    "BoozConfig",
    "parse_booz_surfaces",
    "read_booz_config",
    "resolve_boozmn_path",
    "run_booz_xform",
    "QIOptimizationContext",
    "apply_qi_example_cli_overrides",
    "diagnostic_float",
    "jsonable",
    "make_qi_optimization_context",
    "qi_diagnostics_for_result",
    "qi_engineering_constraint_tuples",
    "qi_stage_modes",
    "run_boundary_reference_preconditioner",
    "run_qi_stage_policy",
    "run_target_helicity_seed_preconditioner",
    "save_raw_seed_initial_artifacts",
    "target_helicity_seed_terms",
    "ExampleData",
    "FixedBoundaryRun",
    "example_paths",
    "load_example",
    "load_input",
    "load_wout",
    "run_free_boundary",
    "run_fixed_boundary",
    "solve_fixed_boundary_from_boundary",
    "save_npz",
    "residual_scalars_from_state",
    "write_wout_from_fixed_boundary_run",
    "wout_from_fixed_boundary_run",
    "booz_xform_inputs_from_state",
    "equilibrium_aspect_ratio_from_state",
    "equilibrium_iota_profiles_from_state",
    "VMECState",
    "pack_state",
    "unpack_state",
    "VMECStatic",
    "build_static",
    "FreeBoundaryRuntimeState",
    "MGridMetadata",
    "MGridData",
    "PreparedMGrid",
    "VacuumBoundaryFields",
    "ExternalBoundarySample",
    "NestorPoissonCache",
    "NestorVmecLikeCache",
    "NestorRuntimeState",
    "NestorSolveResult",
    "boundary_metric_from_rz",
    "covariant_boundary_field_from_cylindrical",
    "contravariant_boundary_field_from_covariant",
    "vacuum_boundary_fields_from_cylindrical",
    "sample_free_boundary_external_field",
    "sample_external_vacuum_diagnostics",
    "nestor_external_only_step",
    "initial_free_boundary_state",
    "interpolate_mgrid_bfield",
    "load_mgrid",
    "prepare_mgrid_for_config",
    "validate_free_boundary_config",
    "initial_guess_from_boundary",
    "extract_axis_override_from_state",
    "BoundaryParamSpec",
    "FixedBoundaryContext",
    "FixedBoundaryExactOptimizer",
    "apply_boundary_params",
    "boundary_param_names",
    "boundary_param_specs",
    "create_x_scale",
    "extend_boundary_for_max_mode",
    "gauss_newton_least_squares",
    "lift_boundary_params",
    "make_qh_residuals_fn",
    "make_qs_residuals_fn",
    "parse_surface_list",
    "prepare_fixed_boundary_context",
    "smooth_min_abs_iota_residual",
    "surface_indices_from_s",
    "surface_indices_from_static",
    "truncate_indata_boundary_modes",
    "AbsMeanIotaFloor",
    "AbsMeanIotaCeiling",
    "AspectRatio",
    "AugmentedLagrangianConstraint",
    "BVector",
    "BDotB",
    "BDotGradV",
    "BetaTotal",
    "BoozerBTarget",
    "BoundaryModeLimits",
    "DMerc",
    "FixedBoundaryOptimizationResult",
    "FixedBoundaryVMEC",
    "GlasserResistiveInterchange",
    "JDotB",
    "JVector",
    "LeastSquaresProblem",
    "LgradB",
    "MagneticWell",
    "MaxElongation",
    "MeanIota",
    "MirrorRatio",
    "VMECMirrorRatio",
    "ObjectiveTerm",
    "OptimizationOutputPaths",
    "QuasiIsodynamicOptions",
    "QuasiIsodynamicResidual",
    "QuasiIsodynamicResidualCeiling",
    "QuasisymmetryRatioResidual",
    "QIObjectiveTerm",
    "RedlBootstrapMismatch",
    "StageContext",
    "ToroidalCurrent",
    "ToroidalCurrentGradient",
    "abs_mean_iota_floor_objective",
    "abs_mean_iota_ceiling_objective",
    "aspect_objective",
    "boozer_b_target_from_wout",
    "describe_boundary_mode_limits",
    "lgradb_objective",
    "interpolate_indata_boundary",
    "least_squares_solve",
    "mean_iota_objective",
    "normalize_boundary_mode_limits",
    "optimization_output_paths",
    "prepare_simple_omnigenity_seed_input",
    "qs_stage_modes",
    "qi_boozer_b_target_objective",
    "qi_lgradb_objective",
    "qi_max_elongation_constraint",
    "qi_max_elongation_objective",
    "qi_mirror_ratio_constraint",
    "qi_mirror_ratio_objective",
    "quasi_isodynamic_field_objective",
    "quasisymmetry_objective",
    "rebuild_for_optimization_resolution",
    "repeated_stage_modes",
    "run_fixed_boundary_objective_optimization",
    "run_quasi_isodynamic_objective_optimization",
    "save_optimization_result",
    "simple_omnigenity_seed_indata",
    "VolavgB",
    "Coords",
    "eval_coords",
    "Geom",
    "eval_geom",
    "ELEMENTARY_CHARGE",
    "Profile",
    "ProfileInputs",
    "ProfilePolynomial",
    "ProfilePressure",
    "ProfileScaled",
    "StandardFiniteBetaProfiles",
    "profiles_from_indata",
    "eval_profiles",
    "pressure_profile_to_vmec_am",
    "profile_to_power_series_coeffs",
    "standard_finite_beta_profiles",
    "standard_pressure_profile",
    "with_pressure_profile",
    "FiniteBetaTargets",
    "finite_beta_global_residuals_from_state",
    "finite_beta_scalars_from_state",
    "glasser_resistive_interchange_from_mercier_terms",
    "jxbforce_profiles_from_realspace",
    "magnetic_well_from_state",
    "magnetic_well_from_vp",
    "mercier_bss_geometry_channels_from_state",
    "mercier_bss_half_mesh_geometry_from_realspace",
    "mercier_bsubs_derivatives_lasym_false",
    "mercier_bsubs_derivatives_lasym_true",
    "mercier_bsubs_full_mesh_from_half_mesh",
    "mercier_bsubs_half_mesh_from_geometry",
    "mercier_bdotk_from_covariant_derivatives",
    "mercier_gpp_from_realspace_geometry",
    "mercier_realspace_geometry_channels_from_state",
    "mercier_surface_integrals_from_realspace",
    "mercier_terms_from_state",
    "mercier_terms_from_profile_integrals",
    "mercier_zeta_half_mesh_from_realspace_geometry",
    "polynomial_profile_and_derivative",
    "redl_bootstrap_geometry_from_state",
    "redl_bootstrap_jdotb",
    "redl_bootstrap_mismatch_from_profiles",
    "redl_bootstrap_mismatch_from_state",
    "trapped_fraction_from_modb_sqrtg",
    "BootstrapCurrentIteration",
    "BootstrapCurrentOptions",
    "BootstrapCurrentResult",
    "apply_current_profile_to_indata",
    "bootstrap_current_fixed_point",
    "bootstrap_current_update_to_indata",
    "damp_current_profile",
    "dpsi_ds_from_vmec_phiedge",
    "integrate_current_derivative",
    "redl_current_derivative_update",
    "redl_current_integrating_factor_update",
    "redl_current_rhs",
    "vmec_current_profile_from_bootstrap_update",
    "dvds_from_sqrtg",
    "cumtrapz_s",
    "volume_from_sqrtg",
    "signgs_from_sqrtg",
    "flux_profiles_from_indata",
    "bsup_from_geom",
    "bsup_from_sqrtg_lambda",
    "b_cartesian_from_state",
    "b2_from_bsup",
    "magnetic_wb_from_state",
    "Summary",
    "print_jacobian_stats",
    "print_summary",
    "summarize_array",
    "summarize_many",
    "vmec_half_mesh_jacobian_from_state",
    "vmec_realspace_analysis",
    "vmec_realspace_geom_from_state",
    "ImplicitLambdaOptions",
    "ImplicitFixedBoundaryOptions",
    "solve_lambda_state_implicit",
    "solve_fixed_boundary_state_implicit",
    "ResidualCheckpointTape",
    "ResidualIterationTrace",
    "build_residual_checkpoint_tape",
    "build_residual_checkpoint_tape_direct",
    "clear_preconditioner_jit_caches",
    "clear_replay_scan_caches",
    "checkpoint_tape_param_jvp",
    "checkpoint_tape_param_vjp",
    "checkpoint_tape_state_jvp",
    "checkpoint_tape_state_jvp_columns",
    "checkpoint_tape_state_vjp",
    "concat_residual_iteration_traces",
    "preconditioned_force_channels_from_raw_forces",
    "preconditioned_force_channels_from_rz_output",
    "raw_force_residual_from_state",
    "replay_residual_checkpoint_step",
    "state_dependent_preconditioner_from_forces",
    "strict_update_accepted_step",
    "strict_update_one_step_from_state",
    "strict_update_velocity_block",
    "strict_update_velocity_limit",
    "strict_update_velocity_state_advance",
    "residual_iteration_trace_from_result",
    "SolveLambdaResult",
    "solve_lambda_gd",
    "SolveFixedBoundaryResult",
    "solve_fixed_boundary_gd",
    "solve_fixed_boundary_lbfgs",
    "solve_fixed_boundary_lbfgs_vmec_residual",
    "solve_fixed_boundary_gn_vmec_residual",
    "solve_fixed_boundary_residual_iter",
    "ForceResiduals",
    "force_residuals_from_state",
    "quasisymmetry_diagnostics_from_state",
    "quasisymmetry_ratio_residual_from_state",
    "quasisymmetry_ratio_residual_from_wout",
    "max_elongation_penalty_from_state",
    "mirror_ratio_penalty_from_boozer_modes",
    "mirror_ratio_penalty_from_boozer_output",
    "quasi_isodynamic_residual_from_boozer_modes",
    "quasi_isodynamic_residual_from_boozer_output",
    "quasi_isodynamic_residual_from_state",
    "legacy_qi_branch_shuffle_diagnostic_from_boozer_output",
    "QI_DIAGNOSTIC_VERSION",
    "QIDiagnosticOptions",
    "QISeedSuitabilityTargets",
    "annotate_qi_seed_suitability",
    "qi_cleanup_candidate_promotable",
    "qi_diagnostics_from_boozer_output",
    "qi_diagnostics_from_state",
    "qi_promotion_score",
    "rank_qi_seed_records",
    "export_vtk_surface_and_fieldline",
]
