"""vmec_jax: a JAX implementation of VMEC2000 for fixed and free-boundary equilibria."""

import os as _os

# Suppress noisy C++ warnings from XLA/PjRt backend (e.g. "Assume version
# compatibility. PjRt-IFRT does not track XLA executable versions.").  Must be
# set before *any* ``import jax`` in the process.  Uses setdefault so the user
# can still override via the environment.
_os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")

# Enable JAX persistent XLA compilation cache.  Kernels compiled for a given
# problem shape are stored on disk and reused across process invocations,
# eliminating the ~9 s cold-compilation cost on warm runs.
import jax as _jax
_jax_cache_dir = _os.path.expanduser("~/.cache/vmec_jax/jax_compile_cache")
_os.makedirs(_jax_cache_dir, exist_ok=True)
_jax.config.update("jax_compilation_cache_dir", _jax_cache_dir)

from . import api
from .namelist import read_indata, InData
from .config import FreeBoundaryConfig, VMECConfig, load_config
from .modes import ModeTable, vmec_mode_table, nyquist_mode_table, default_grid_sizes
from .grids import AngleGrid, make_angle_grid
from .boundary import (
    BoundaryCoeffs,
    boundary_from_indata,
    boundary_aspect_ratio,
    boundary_aspect_ratio_from_static,
)
from .fourier import (
    HelicalBasis,
    build_helical_basis,
    eval_fourier,
    eval_fourier_dtheta,
    eval_fourier_dzeta_phys,
)
from .plotting import (
    SurfaceData,
    axis_rz_from_wout,
    axis_rz_from_wout_physical,
    axis_rz_from_state_physical,
    bmag_from_wout,
    bmag_from_wout_physical,
    bmag_from_state_physical,
    bmag_from_state_vmec_realspace,
    bsup_from_wout,
    bsub_from_wout,
    closed_theta_grid,
    fix_matplotlib_3d,
    profiles_from_wout,
    select_zeta_slices,
    surface_data_from_wout,
    surface_rz_from_wout,
    surface_rz_from_wout_physical,
    surface_rz_from_state,
    surface_rz_from_state_physical,
    surface_stack,
    vmecplot2_bmag_grid,
    vmecplot2_cross_section_indices,
    vmecplot2_lcfs_3d_grid,
    vmecplot2_surface_grid,
    write_axisym_overview,
    write_bmag_parity_figures,
    write_bsub_parity_figures,
    write_bsup_parity_figures,
    zeta_grid,
    zeta_grid_field_period,
)
from .driver import (
    ExampleData,
    FixedBoundaryRun,
    example_paths,
    load_example,
    load_input,
    load_wout,
    run_fixed_boundary,
    solve_fixed_boundary_from_boundary,
    save_npz,
    residual_scalars_from_state,
    write_wout_from_fixed_boundary_run,
    wout_from_fixed_boundary_run,
)
from .booz_input import booz_xform_inputs_from_state
from .wout import equilibrium_aspect_ratio_from_state, equilibrium_iota_profiles_from_state
from .state import VMECState, pack_state, unpack_state
from .static import VMECStatic, build_static
from .free_boundary import (
    FreeBoundaryRuntimeState,
    MGridMetadata,
    MGridData,
    PreparedMGrid,
    VacuumBoundaryFields,
    ExternalBoundarySample,
    NestorPoissonCache,
    NestorVmecLikeCache,
    NestorRuntimeState,
    NestorSolveResult,
    boundary_metric_from_rz,
    covariant_boundary_field_from_cylindrical,
    contravariant_boundary_field_from_covariant,
    vacuum_boundary_fields_from_cylindrical,
    sample_external_vacuum_diagnostics,
    nestor_external_only_step,
    initial_free_boundary_state,
    interpolate_mgrid_bfield,
    load_mgrid,
    prepare_mgrid_for_config,
    validate_free_boundary_config,
)
from .init_guess import extract_axis_override_from_state, initial_guess_from_boundary
from .optimization import (
    BoundaryParamSpec,
    FixedBoundaryContext,
    apply_boundary_params,
    boundary_param_names,
    boundary_param_specs,
    gauss_newton_least_squares,
    parse_surface_list,
    prepare_fixed_boundary_context,
    surface_indices_from_s,
    surface_indices_from_static,
)
from .coords import Coords, eval_coords
from .geom import Geom, eval_geom
from .profiles import ProfileInputs, profiles_from_indata, eval_profiles
from .integrals import dvds_from_sqrtg, cumtrapz_s, volume_from_sqrtg
from .field import bsup_from_geom, bsup_from_sqrtg_lambda, b2_from_bsup, signgs_from_sqrtg
from .energy import magnetic_wb_from_state, flux_profiles_from_indata
from .diagnostics import Summary, print_jacobian_stats, print_summary, summarize_array, summarize_many
from .vmec_jacobian import vmec_half_mesh_jacobian_from_state
from .vmec_realspace import vmec_realspace_analysis, vmec_realspace_geom_from_state
from .implicit import (
    ImplicitFixedBoundaryOptions,
    ImplicitLambdaOptions,
    solve_fixed_boundary_state_implicit,
    solve_lambda_state_implicit,
)
from .discrete_adjoint import (
    ResidualCheckpointTape,
    ResidualIterationTrace,
    build_residual_checkpoint_tape,
    build_residual_checkpoint_tape_direct,
    clear_replay_scan_caches,
    checkpoint_tape_param_jvp,
    checkpoint_tape_param_vjp,
    checkpoint_tape_state_jvp,
    checkpoint_tape_state_jvp_columns,
    checkpoint_tape_state_vjp,
    concat_residual_iteration_traces,
    preconditioned_force_channels_from_raw_forces,
    preconditioned_force_channels_from_rz_output,
    raw_force_residual_from_state,
    replay_residual_checkpoint_step,
    state_dependent_preconditioner_from_forces,
    strict_update_accepted_step,
    strict_update_one_step_from_state,
    strict_update_velocity_block,
    strict_update_velocity_limit,
    strict_update_velocity_state_advance,
    residual_iteration_trace_from_result,
)
from .solve import (
    SolveFixedBoundaryResult,
    SolveLambdaResult,
    solve_fixed_boundary_gd,
    solve_fixed_boundary_lbfgs,
    solve_fixed_boundary_lbfgs_vmec_residual,
    solve_fixed_boundary_gn_vmec_residual,
    solve_fixed_boundary_residual_iter,
    solve_lambda_gd,
)
from .residuals import ForceResiduals, force_residuals_from_state
from .quasisymmetry import (
    quasisymmetry_diagnostics_from_state,
    quasisymmetry_ratio_residual_from_state,
    quasisymmetry_ratio_residual_from_wout,
)
from .visualization import export_vtk_surface_and_fieldline

__all__ = [
    "api",
    "read_indata",
    "InData",
    "FreeBoundaryConfig",
    "VMECConfig",
    "load_config",
    "ModeTable",
    "vmec_mode_table",
    "nyquist_mode_table",
    "default_grid_sizes",
    "AngleGrid",
    "make_angle_grid",
    "BoundaryCoeffs",
    "boundary_from_indata",
    "boundary_aspect_ratio",
    "boundary_aspect_ratio_from_static",
    "HelicalBasis",
    "build_helical_basis",
    "eval_fourier",
    "eval_fourier_dtheta",
    "eval_fourier_dzeta_phys",
    "SurfaceData",
    "axis_rz_from_wout",
    "axis_rz_from_wout_physical",
    "axis_rz_from_state_physical",
    "bmag_from_wout",
    "bmag_from_wout_physical",
    "bmag_from_state_physical",
    "bmag_from_state_vmec_realspace",
    "bsup_from_wout",
    "bsub_from_wout",
    "closed_theta_grid",
    "fix_matplotlib_3d",
    "profiles_from_wout",
    "select_zeta_slices",
    "surface_data_from_wout",
    "surface_rz_from_wout",
    "surface_rz_from_wout_physical",
    "surface_rz_from_state",
    "surface_rz_from_state_physical",
    "surface_stack",
    "vmecplot2_bmag_grid",
    "vmecplot2_cross_section_indices",
    "vmecplot2_lcfs_3d_grid",
    "vmecplot2_surface_grid",
    "write_axisym_overview",
    "write_bmag_parity_figures",
    "write_bsub_parity_figures",
    "write_bsup_parity_figures",
    "zeta_grid",
    "zeta_grid_field_period",
    "ExampleData",
    "FixedBoundaryRun",
    "example_paths",
    "load_example",
    "load_input",
    "load_wout",
    "run_fixed_boundary",
    "solve_fixed_boundary_from_boundary",
    "save_npz",
    "residual_scalars_from_state",
    "write_wout_from_fixed_boundary_run",
    "wout_from_fixed_boundary_run",
    "booz_xform_inputs_from_state",
    "equilibrium_aspect_ratio_from_state",
    "equilibrium_iota_profiles_from_state",
    "VMECState",
    "pack_state",
    "unpack_state",
    "VMECStatic",
    "build_static",
    "FreeBoundaryRuntimeState",
    "MGridMetadata",
    "MGridData",
    "PreparedMGrid",
    "VacuumBoundaryFields",
    "ExternalBoundarySample",
    "NestorPoissonCache",
    "NestorVmecLikeCache",
    "NestorRuntimeState",
    "NestorSolveResult",
    "boundary_metric_from_rz",
    "covariant_boundary_field_from_cylindrical",
    "contravariant_boundary_field_from_covariant",
    "vacuum_boundary_fields_from_cylindrical",
    "sample_external_vacuum_diagnostics",
    "nestor_external_only_step",
    "initial_free_boundary_state",
    "interpolate_mgrid_bfield",
    "load_mgrid",
    "prepare_mgrid_for_config",
    "validate_free_boundary_config",
    "initial_guess_from_boundary",
    "extract_axis_override_from_state",
    "BoundaryParamSpec",
    "FixedBoundaryContext",
    "apply_boundary_params",
    "boundary_param_names",
    "boundary_param_specs",
    "gauss_newton_least_squares",
    "parse_surface_list",
    "prepare_fixed_boundary_context",
    "surface_indices_from_s",
    "surface_indices_from_static",
    "Coords",
    "eval_coords",
    "Geom",
    "eval_geom",
    "ProfileInputs",
    "profiles_from_indata",
    "eval_profiles",
    "dvds_from_sqrtg",
    "cumtrapz_s",
    "volume_from_sqrtg",
    "signgs_from_sqrtg",
    "flux_profiles_from_indata",
    "bsup_from_geom",
    "bsup_from_sqrtg_lambda",
    "b2_from_bsup",
    "magnetic_wb_from_state",
    "Summary",
    "print_jacobian_stats",
    "print_summary",
    "summarize_array",
    "summarize_many",
    "vmec_half_mesh_jacobian_from_state",
    "vmec_realspace_analysis",
    "vmec_realspace_geom_from_state",
    "ImplicitLambdaOptions",
    "ImplicitFixedBoundaryOptions",
    "solve_lambda_state_implicit",
    "solve_fixed_boundary_state_implicit",
    "ResidualCheckpointTape",
    "ResidualIterationTrace",
    "build_residual_checkpoint_tape",
    "build_residual_checkpoint_tape_direct",
    "clear_replay_scan_caches",
    "checkpoint_tape_param_jvp",
    "checkpoint_tape_param_vjp",
    "checkpoint_tape_state_jvp",
    "checkpoint_tape_state_jvp_columns",
    "checkpoint_tape_state_vjp",
    "concat_residual_iteration_traces",
    "preconditioned_force_channels_from_raw_forces",
    "preconditioned_force_channels_from_rz_output",
    "raw_force_residual_from_state",
    "replay_residual_checkpoint_step",
    "state_dependent_preconditioner_from_forces",
    "strict_update_accepted_step",
    "strict_update_one_step_from_state",
    "strict_update_velocity_block",
    "strict_update_velocity_limit",
    "strict_update_velocity_state_advance",
    "residual_iteration_trace_from_result",
    "SolveLambdaResult",
    "solve_lambda_gd",
    "SolveFixedBoundaryResult",
    "solve_fixed_boundary_gd",
    "solve_fixed_boundary_lbfgs",
    "solve_fixed_boundary_lbfgs_vmec_residual",
    "solve_fixed_boundary_gn_vmec_residual",
    "solve_fixed_boundary_residual_iter",
    "ForceResiduals",
    "force_residuals_from_state",
    "quasisymmetry_diagnostics_from_state",
    "quasisymmetry_ratio_residual_from_state",
    "quasisymmetry_ratio_residual_from_wout",
    "export_vtk_surface_and_fieldline",
]
