"""Public, user-facing API for vmec_jax.

This module intentionally re-exports a small set of functions that cover the
common workflows:

- I/O: load input, read/write wout
- Solve: fixed- and free-boundary drivers
- Plotting: VMEC-style surfaces and magnetic-field magnitude

Advanced users can import lower-level kernels directly from submodules.
"""

from __future__ import annotations

from .namelist import minimal_fixed_boundary_indata, read_indata, write_indata
from .driver import (
    ExampleData,
    FixedBoundaryRun,
    example_paths,
    load_example,
    load_input,
    load_wout,
    run_free_boundary,
    run_fixed_boundary,
    residual_scalars_from_state,
    wout_from_fixed_boundary_run,
    write_wout_from_fixed_boundary_run,
)
from .boundary import boundary_from_input_convention, boundary_input_from_indata
from .booz_input import booz_xform_inputs_from_state
from .field import b_cartesian_from_state, signgs_from_sqrtg
from .energy import flux_profiles_from_indata
from .finite_beta import (
    FiniteBetaTargets,
    finite_beta_global_residuals_from_state,
    finite_beta_scalars_from_state,
    magnetic_well_from_state,
)
from .optimization_workflow import (
    AbsMeanIotaFloor,
    AbsMeanIotaCeiling,
    AspectRatio,
    AugmentedLagrangianConstraint,
    BDotB,
    BDotGradV,
    BVector,
    BetaTotal,
    BoozerBTarget,
    DMerc,
    FixedBoundaryVMEC,
    JDotB,
    JVector,
    LeastSquaresProblem,
    LgradB,
    MagneticWell,
    MaxElongation,
    MeanIota,
    MirrorRatio,
    OptimizationOutputPaths,
    QuasiIsodynamicOptions,
    QuasiIsodynamicResidual,
    QuasiIsodynamicResidualCeiling,
    QuasisymmetryRatioResidual,
    RedlBootstrapMismatch,
    ToroidalCurrent,
    ToroidalCurrentGradient,
    VolavgB,
    boozer_b_target_from_wout,
    least_squares_solve,
    optimization_output_paths,
    prepare_simple_omnigenity_seed_input,
    qi_boozer_b_target_objective,
    qi_max_elongation_constraint,
    qi_mirror_ratio_constraint,
    qs_stage_modes,
    repeated_stage_modes,
    save_optimization_result,
    simple_omnigenity_seed_indata,
)
from .quasi_isodynamic import (
    lgradb_from_state,
    lgradb_penalty_from_state,
    max_elongation_penalty_from_state,
    mirror_ratio_penalty_from_boozer_modes,
    mirror_ratio_penalty_from_boozer_output,
    quasi_isodynamic_residual_from_boozer_modes,
    quasi_isodynamic_residual_from_boozer_output,
    quasi_isodynamic_residual_from_state,
)
from .plotting import (
    bmag_from_state_physical,
    bmag_from_wout,
    closed_theta_grid,
    fix_matplotlib_3d,
    profiles_from_wout,
    plot_3d_boundary_comparison,
    plot_bmag_contours,
    plot_boozer_bmag_contours_from_state,
    plot_objective_history,
    plot_wout,
    surface_rz_from_wout_physical,
    surface_stack,
    vmecplot2_bmag_grid,
    vmecplot2_cross_section_indices,
    vmecplot2_lcfs_3d_grid,
    vmecplot2_surface_grid,
    write_axisym_overview,
    write_bmag_parity_figures,
    write_bsub_parity_figures,
    write_bsup_parity_figures,
    zeta_grid,
    zeta_grid_field_period,
)
from .qi_diagnostics import (
    QIDiagnosticOptions,
    QISeedSuitabilityTargets,
    annotate_qi_seed_suitability,
    qi_cleanup_candidate_promotable,
    qi_diagnostics_from_boozer_output,
    qi_diagnostics_from_state,
    qi_promotion_score,
    rank_qi_seed_records,
)
from .visualization import export_vtk_surface_and_fieldline
from .wout import read_wout, state_from_wout

__all__ = [
    # Driver / solve
    "ExampleData",
    "FixedBoundaryRun",
    "example_paths",
    "load_example",
    "load_input",
    "load_wout",
    "run_free_boundary",
    "run_fixed_boundary",
    "residual_scalars_from_state",
    "wout_from_fixed_boundary_run",
    "write_wout_from_fixed_boundary_run",
    "boundary_input_from_indata",
    "boundary_from_input_convention",
    "read_indata",
    "write_indata",
    "minimal_fixed_boundary_indata",
    "booz_xform_inputs_from_state",
    "lgradb_from_state",
    "lgradb_penalty_from_state",
    "max_elongation_penalty_from_state",
    "mirror_ratio_penalty_from_boozer_modes",
    "mirror_ratio_penalty_from_boozer_output",
    "quasi_isodynamic_residual_from_boozer_modes",
    "quasi_isodynamic_residual_from_boozer_output",
    "quasi_isodynamic_residual_from_state",
    "QIDiagnosticOptions",
    "QISeedSuitabilityTargets",
    "annotate_qi_seed_suitability",
    "qi_cleanup_candidate_promotable",
    "qi_diagnostics_from_boozer_output",
    "qi_diagnostics_from_state",
    "qi_promotion_score",
    "rank_qi_seed_records",
    # Optimization workflow helpers used by examples
    "FixedBoundaryVMEC",
    "LeastSquaresProblem",
    "AspectRatio",
    "AugmentedLagrangianConstraint",
    "MeanIota",
    "AbsMeanIotaFloor",
    "AbsMeanIotaCeiling",
    "QuasisymmetryRatioResidual",
    "QuasiIsodynamicOptions",
    "QuasiIsodynamicResidual",
    "QuasiIsodynamicResidualCeiling",
    "MirrorRatio",
    "OptimizationOutputPaths",
    "MaxElongation",
    "LgradB",
    "BoozerBTarget",
    "boozer_b_target_from_wout",
    "qi_boozer_b_target_objective",
    "qi_max_elongation_constraint",
    "qi_mirror_ratio_constraint",
    "BetaTotal",
    "VolavgB",
    "BDotB",
    "BDotGradV",
    "BVector",
    "JDotB",
    "JVector",
    "ToroidalCurrent",
    "ToroidalCurrentGradient",
    "RedlBootstrapMismatch",
    "FiniteBetaTargets",
    "finite_beta_global_residuals_from_state",
    "finite_beta_scalars_from_state",
    "least_squares_solve",
    "optimization_output_paths",
    "prepare_simple_omnigenity_seed_input",
    "qs_stage_modes",
    "repeated_stage_modes",
    "save_optimization_result",
    "simple_omnigenity_seed_indata",
    # Plotting helpers
    "bmag_from_state_physical",
    "bmag_from_wout",
    "closed_theta_grid",
    "fix_matplotlib_3d",
    "profiles_from_wout",
    "plot_3d_boundary_comparison",
    "plot_bmag_contours",
    "plot_boozer_bmag_contours_from_state",
    "plot_objective_history",
    "plot_wout",
    "surface_rz_from_wout_physical",
    "surface_stack",
    "vmecplot2_bmag_grid",
    "vmecplot2_cross_section_indices",
    "vmecplot2_lcfs_3d_grid",
    "vmecplot2_surface_grid",
    "write_axisym_overview",
    "write_bmag_parity_figures",
    "write_bsub_parity_figures",
    "write_bsup_parity_figures",
    "zeta_grid",
    "zeta_grid_field_period",
    # Field helpers
    "b_cartesian_from_state",
    "signgs_from_sqrtg",
    "flux_profiles_from_indata",
    "magnetic_well_from_state",
    "MagneticWell",
    "DMerc",
    # Visualization helpers
    "export_vtk_surface_and_fieldline",
    # Low-friction wout access for plotting
    "read_wout",
    "state_from_wout",
]
