"""Free-boundary solve helpers, diagnostics, and derivative reports."""

from .derivatives import (
    DEFAULT_FREE_BOUNDARY_DERIVATIVE_OUTPUTS,
    FreeBoundaryDerivativeOptions,
    canonical_free_boundary_output_keys,
    coil_direction,
    contract_free_boundary_vjp,
    free_boundary_value_and_jacobian,
    free_boundary_value_and_jvp,
)
from .reduced_controls import (
    ReducedControlMap,
    ReducedControlState,
    ReducedControlStep,
    reduced_control_decode,
    reduced_control_least_squares_step,
    reduced_control_pullback,
)
from .control import (
    FreeBoundaryNativeSplineForce,
    FreeBoundaryNativeSplineState,
    FreeBoundaryNativeSplineUpdate,
    FreeBoundaryReducedEdgeState,
    free_boundary_reduced_edge_state_from_vmec_state,
    free_boundary_reduced_edge_state_to_vmec_state,
)
from .native_state import (
    FreeBoundaryNativeSplineVectorStep,
    FreeBoundaryNativeSplineUnknownVector,
    free_boundary_native_spline_unknown_vector_from_vmec_state,
    free_boundary_native_spline_project_vmec_delta_jax,
    free_boundary_native_spline_vector_projected_residual_jax,
    free_boundary_native_spline_vector_residual_jax,
    free_boundary_native_spline_vector_to_vmec_state_jax,
    free_boundary_native_spline_vector_edge_step,
)
from .native_problem import (
    FreeBoundaryNativeSplineDenseSolve,
    FreeBoundaryNativeSplineDenseStep,
    FreeBoundaryNativeSplineMatrixFreeSolve,
    FreeBoundaryNativeSplineMatrixFreeStep,
    FreeBoundaryNativeSplineResidualProblem,
    free_boundary_native_spline_dense_gauss_newton_solve_jax,
    free_boundary_native_spline_dense_gauss_newton_step_jax,
    free_boundary_native_spline_force_blocks_to_state_residual,
    free_boundary_native_spline_matrix_free_normal_solve_jax,
    free_boundary_native_spline_matrix_free_normal_step_jax,
)

__all__ = [
    "DEFAULT_FREE_BOUNDARY_DERIVATIVE_OUTPUTS",
    "FreeBoundaryDerivativeOptions",
    "FreeBoundaryNativeSplineForce",
    "FreeBoundaryNativeSplineState",
    "FreeBoundaryNativeSplineUpdate",
    "FreeBoundaryNativeSplineUnknownVector",
    "FreeBoundaryNativeSplineVectorStep",
    "FreeBoundaryNativeSplineDenseSolve",
    "FreeBoundaryNativeSplineDenseStep",
    "FreeBoundaryNativeSplineMatrixFreeSolve",
    "FreeBoundaryNativeSplineMatrixFreeStep",
    "FreeBoundaryNativeSplineResidualProblem",
    "FreeBoundaryReducedEdgeState",
    "ReducedControlMap",
    "ReducedControlState",
    "ReducedControlStep",
    "canonical_free_boundary_output_keys",
    "coil_direction",
    "contract_free_boundary_vjp",
    "free_boundary_value_and_jacobian",
    "free_boundary_value_and_jvp",
    "free_boundary_native_spline_unknown_vector_from_vmec_state",
    "free_boundary_native_spline_project_vmec_delta_jax",
    "free_boundary_native_spline_vector_projected_residual_jax",
    "free_boundary_native_spline_vector_residual_jax",
    "free_boundary_native_spline_vector_to_vmec_state_jax",
    "free_boundary_native_spline_vector_edge_step",
    "free_boundary_native_spline_dense_gauss_newton_solve_jax",
    "free_boundary_native_spline_dense_gauss_newton_step_jax",
    "free_boundary_native_spline_force_blocks_to_state_residual",
    "free_boundary_native_spline_matrix_free_normal_solve_jax",
    "free_boundary_native_spline_matrix_free_normal_step_jax",
    "free_boundary_reduced_edge_state_from_vmec_state",
    "free_boundary_reduced_edge_state_to_vmec_state",
    "reduced_control_decode",
    "reduced_control_least_squares_step",
    "reduced_control_pullback",
]
