"""Open-field-line magnetic-mirror equilibrium support.

The mirror backend uses ``(s, theta, xi)`` coordinates: a VMEC-like radial
mesh, a periodic poloidal angle, and a nonperiodic axial coordinate.  It is a
separate topology from toroidal VMEC, but shares JAX kernels, coil fields,
solver controls, and diagnostics with :mod:`vmec_jax.core`.

Only implemented, tested contracts are exported here.  Solver, vacuum, and
output APIs will be added as their corresponding M2-M6 plan gates land.
"""

from .basis import ChebyshevBasis, MirrorGrid, ThetaBasis, build_mirror_grid
from .diagnostics import AxisymmetricBetaDiagnostics, summarize_axisymmetric_beta_scan
from .geometry import (
    ContravariantField,
    MirrorGeometry,
    contravariant_field,
    divergence_b,
    evaluate_geometry,
    magnetic_field_squared,
)
from .exterior import (
    ClosedMirrorSurface,
    build_closed_mirror_surface,
    laplace_double_layer_off_surface,
    laplace_green_boundary_residual,
    laplace_green_representation_off_surface,
    laplace_single_layer_off_surface,
    laplace_single_layer_gradient_off_surface,
)
from .forces import (
    AnisotropicMirrorEnergy,
    AnisotropicForceResidual,
    IsotropicForceResidual,
    InterfaceResidual,
    MirrorEnergy,
    VariationalResidual,
    anisotropic_fixed_boundary_energy_gradient,
    anisotropic_fixed_boundary_variational_residual,
    anisotropic_force_residual,
    anisotropic_mirror_energy,
    fixed_boundary_energy_gradient,
    fixed_boundary_variational_residual,
    isotropic_force_residual,
    interface_residual,
    mass_profile_from_pressure,
    mirror_energy,
)
from .model import (
    MIRROR_INPUT_SCHEMA,
    MIRROR_OUTPUT_SCHEMA,
    AnisotropyIndicators,
    BiMaxwellianPressureClosure,
    EndCondition,
    MirrorBoundary,
    MirrorConfig,
    MirrorResolution,
    MirrorState,
    IsotropicPressureClosure,
    PressureClosure,
    PressureMoments,
    TabulatedPressureClosure,
    anisotropy_indicators,
    project_fixed_boundary_state,
)
from .solver import (
    MirrorConvergenceError,
    MirrorSolveResult,
    SeparableMirrorPreconditioner,
    solve_anisotropic_fixed_boundary_cli,
    solve_fixed_boundary_cli,
)
from .restart import (
    FreeBoundaryRestart,
    load_free_boundary_restart,
    save_free_boundary_restart,
)
from .free_boundary import FreeBoundaryMirrorResult, solve_axisymmetric_free_boundary_cli
from .vacuum import (
    VacuumField,
    VacuumGeometry,
    VacuumGrid,
    VacuumSolveResult,
    build_vacuum_grid,
    evaluate_vacuum_field,
    evaluate_vacuum_geometry,
    external_field_from_coils,
    external_field_from_source,
    solve_vacuum_potential,
    vacuum_energy_functional,
    vacuum_laplacian,
)
from .continuation import interpolate_fixed_boundary_state, solve_axisymmetric_beta_scan_cli

__all__ = [
    "MIRROR_INPUT_SCHEMA",
    "MIRROR_OUTPUT_SCHEMA",
    "ChebyshevBasis",
    "ClosedMirrorSurface",
    "ContravariantField",
    "EndCondition",
    "AnisotropyIndicators",
    "AnisotropicMirrorEnergy",
    "AnisotropicForceResidual",
    "AxisymmetricBetaDiagnostics",
    "BiMaxwellianPressureClosure",
    "IsotropicForceResidual",
    "InterfaceResidual",
    "IsotropicPressureClosure",
    "MirrorBoundary",
    "MirrorConfig",
    "MirrorConvergenceError",
    "MirrorGeometry",
    "MirrorGrid",
    "MirrorEnergy",
    "MirrorResolution",
    "MirrorSolveResult",
    "MirrorState",
    "PressureClosure",
    "PressureMoments",
    "ThetaBasis",
    "TabulatedPressureClosure",
    "VariationalResidual",
    "VacuumField",
    "FreeBoundaryMirrorResult",
    "FreeBoundaryRestart",
    "VacuumGeometry",
    "VacuumGrid",
    "VacuumSolveResult",
    "SeparableMirrorPreconditioner",
    "build_mirror_grid",
    "build_closed_mirror_surface",
    "build_vacuum_grid",
    "anisotropy_indicators",
    "anisotropic_fixed_boundary_energy_gradient",
    "anisotropic_fixed_boundary_variational_residual",
    "anisotropic_force_residual",
    "anisotropic_mirror_energy",
    "contravariant_field",
    "divergence_b",
    "evaluate_geometry",
    "evaluate_vacuum_field",
    "evaluate_vacuum_geometry",
    "external_field_from_coils",
    "external_field_from_source",
    "fixed_boundary_energy_gradient",
    "fixed_boundary_variational_residual",
    "isotropic_force_residual",
    "interface_residual",
    "interpolate_fixed_boundary_state",
    "magnetic_field_squared",
    "mass_profile_from_pressure",
    "load_free_boundary_restart",
    "laplace_double_layer_off_surface",
    "laplace_green_boundary_residual",
    "laplace_green_representation_off_surface",
    "laplace_single_layer_off_surface",
    "laplace_single_layer_gradient_off_surface",
    "mirror_energy",
    "project_fixed_boundary_state",
    "solve_anisotropic_fixed_boundary_cli",
    "solve_fixed_boundary_cli",
    "solve_vacuum_potential",
    "solve_axisymmetric_free_boundary_cli",
    "solve_axisymmetric_beta_scan_cli",
    "save_free_boundary_restart",
    "summarize_axisymmetric_beta_scan",
    "vacuum_energy_functional",
    "vacuum_laplacian",
]
