"""Small public surface for experimental mirror-geometry primitives."""

from .core.basis import ChebyshevLobattoBasis, ThetaFourierBasis
from .core.boundary import MirrorBoundary
from .core.config import MirrorConfig, MirrorResolution
from .core.grids import MirrorGrid, make_mirror_grid
from .core.profiles import IPrimeProfile, PressureProfile, PsiPrimeProfile
from .core.state import MirrorState3D, MirrorStateAxisym
from .free_boundary import (
    MirrorCircularCoils,
    MirrorExternalFieldSample,
    MirrorFreeBoundaryBetaCase,
    MirrorFreeBoundaryCircularCoilScan,
    MirrorFreeBoundaryLeastSquaresStep,
    MirrorFreeBoundaryResidual,
    MirrorLCFSDiagnostic,
    MirrorLCFSMerit,
    MirrorLCFSResidual,
    MirrorLCFSUpdateProposal,
    initial_mirror_boundary_from_circular_coil_scan,
    load_mirror_free_boundary_circular_coil_scan,
    make_mirror_free_boundary_beta_cases,
    make_mirror_free_boundary_circular_coil_scan,
    mirror_boundary_from_external_axis_field,
    mirror_circular_coils_to_direct_params,
    mirror_external_bnormal,
    mirror_external_pressure_balance_response,
    mirror_free_boundary_least_squares_step,
    mirror_free_boundary_residual,
    mirror_free_boundary_residual_jacobian_finite_difference,
    mirror_lcfs_diagnostic,
    mirror_lcfs_diagnostic_from_arrays,
    mirror_lcfs_merit,
    mirror_lcfs_residual,
    propose_axisymmetric_mirror_lcfs_update,
    propose_axisymmetric_mirror_lcfs_scale_update,
    propose_axisymmetric_mirror_lcfs_noop_update,
    propose_axisymmetric_mirror_lcfs_bnormal_update,
    propose_axisymmetric_mirror_lcfs_mixed_update,
    propose_axisymmetric_mirror_lcfs_candidate_set,
    sample_mirror_axis_external_field,
    sample_mirror_boundary_external_field,
    write_mirror_free_boundary_circular_coil_scan,
)
from .io.mout import is_mirror_output, load_mirror_output, read_mirror_output, write_mirror_output
from .io.schema import MirrorOutput
from .plotting.export import mirror_axisym_slice_to_csv, mirror_output_to_npz, plot_mirror_output
from .solvers.fixed_boundary.api import (
    FixedBoundaryOptimizerSummary,
    MirrorFixedBoundaryResult,
    MirrorSolveOptions,
    run_mirror_fixed_boundary,
)
from .solvers.fixed_boundary.reduced import (
    axisym_reduced_implicit_adjoint_jax,
    axisym_reduced_implicit_polynomial_boundary_sensitivity_jax,
    axisym_reduced_implicit_polynomial_boundary_state_jax,
    axisym_reduced_implicit_profile_sensitivity_jax,
    axisym_reduced_implicit_profile_state_jax,
    axisym_reduced_implicit_pressure_sensitivity_jax,
    axisym_reduced_implicit_pressure_state_jax,
    axisym_reduced_implicit_source_state_jax,
    axisym_reduced_implicit_state_sensitivity_jax,
    axisym_reduced_polynomial_boundary_radius_jax,
    axisym_reduced_residual_polynomial_boundary_jacobian_jax,
    axisym_reduced_residual_profile_jacobian_jax,
    axisym_reduced_residual_pressure_jacobian_jax,
    axisym_reduced_residual_matvec_jax,
    axisym_reduced_residual_jacobian_jax,
    axisym_reduced_residual_jax,
    axisym_reduced_residual_linear_solve_jax,
)
from .validation.coils import (
    circular_loop_field_rz,
    circular_loop_on_axis_bz,
    mirror_boundary_from_on_axis_bz,
    mirror_boundary_from_two_coil_flux_tube,
    on_axis_mirror_ratio,
    two_coil_field_rz,
    two_coil_on_axis_bz,
    two_coil_on_axis_mirror_ratio,
)
from .validation.wham import (
    build_wham_loop_table,
    load_wham_fixture,
    mirror_boundary_from_vacuum_flux_tube,
    wham_on_axis_mirror_ratio,
    wham_reference_field,
    wham_vacuum_field_rz,
)


__all__ = [
    "ChebyshevLobattoBasis",
    "FixedBoundaryOptimizerSummary",
    "IPrimeProfile",
    "MirrorBoundary",
    "MirrorCircularCoils",
    "MirrorConfig",
    "MirrorExternalFieldSample",
    "MirrorFreeBoundaryBetaCase",
    "MirrorFreeBoundaryCircularCoilScan",
    "MirrorFreeBoundaryLeastSquaresStep",
    "MirrorFreeBoundaryResidual",
    "MirrorFixedBoundaryResult",
    "MirrorGrid",
    "MirrorLCFSDiagnostic",
    "MirrorLCFSMerit",
    "MirrorLCFSResidual",
    "MirrorLCFSUpdateProposal",
    "MirrorOutput",
    "MirrorResolution",
    "MirrorSolveOptions",
    "MirrorState3D",
    "MirrorStateAxisym",
    "PressureProfile",
    "PsiPrimeProfile",
    "ThetaFourierBasis",
    "axisym_reduced_residual_jacobian_jax",
    "axisym_reduced_implicit_adjoint_jax",
    "axisym_reduced_implicit_polynomial_boundary_sensitivity_jax",
    "axisym_reduced_implicit_polynomial_boundary_state_jax",
    "axisym_reduced_implicit_profile_sensitivity_jax",
    "axisym_reduced_implicit_profile_state_jax",
    "axisym_reduced_implicit_pressure_sensitivity_jax",
    "axisym_reduced_implicit_pressure_state_jax",
    "axisym_reduced_implicit_source_state_jax",
    "axisym_reduced_implicit_state_sensitivity_jax",
    "axisym_reduced_polynomial_boundary_radius_jax",
    "axisym_reduced_residual_polynomial_boundary_jacobian_jax",
    "axisym_reduced_residual_profile_jacobian_jax",
    "axisym_reduced_residual_pressure_jacobian_jax",
    "axisym_reduced_residual_jax",
    "axisym_reduced_residual_linear_solve_jax",
    "axisym_reduced_residual_matvec_jax",
    "circular_loop_field_rz",
    "circular_loop_on_axis_bz",
    "initial_mirror_boundary_from_circular_coil_scan",
    "is_mirror_output",
    "load_mirror_output",
    "load_mirror_free_boundary_circular_coil_scan",
    "load_wham_fixture",
    "make_mirror_grid",
    "make_mirror_free_boundary_beta_cases",
    "make_mirror_free_boundary_circular_coil_scan",
    "mirror_axisym_slice_to_csv",
    "mirror_boundary_from_external_axis_field",
    "mirror_boundary_from_on_axis_bz",
    "mirror_boundary_from_two_coil_flux_tube",
    "mirror_boundary_from_vacuum_flux_tube",
    "mirror_circular_coils_to_direct_params",
    "mirror_external_bnormal",
    "mirror_external_pressure_balance_response",
    "mirror_free_boundary_least_squares_step",
    "mirror_free_boundary_residual",
    "mirror_free_boundary_residual_jacobian_finite_difference",
    "mirror_lcfs_diagnostic",
    "mirror_lcfs_diagnostic_from_arrays",
    "mirror_lcfs_merit",
    "mirror_lcfs_residual",
    "mirror_output_to_npz",
    "propose_axisymmetric_mirror_lcfs_update",
    "propose_axisymmetric_mirror_lcfs_scale_update",
    "propose_axisymmetric_mirror_lcfs_noop_update",
    "propose_axisymmetric_mirror_lcfs_bnormal_update",
    "propose_axisymmetric_mirror_lcfs_mixed_update",
    "propose_axisymmetric_mirror_lcfs_candidate_set",
    "plot_mirror_output",
    "read_mirror_output",
    "run_mirror_fixed_boundary",
    "sample_mirror_axis_external_field",
    "sample_mirror_boundary_external_field",
    "build_wham_loop_table",
    "on_axis_mirror_ratio",
    "two_coil_field_rz",
    "two_coil_on_axis_bz",
    "two_coil_on_axis_mirror_ratio",
    "wham_on_axis_mirror_ratio",
    "wham_reference_field",
    "wham_vacuum_field_rz",
    "write_mirror_output",
    "write_mirror_free_boundary_circular_coil_scan",
]
